PwA Store 2.0/config/urls.py
# config/urls.py
from django.contrib import admin
from django.urls import path, include # new
from django.conf import settings #new
from django.conf.urls.static import static #new

urlpatterns = [
    path('', include('products.urls', namespace='mainapp')), #new
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')), # new
    path('accounts/',include('accounts.urls')), # new
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  #new

PwA Store 2.0/products/urls.py
# products/urls.py
from django.urls import path
from . views import Home,ProductListView
from cart.views import add_to_cart, CartListView, increase_cart, decrease_cart #new
from orders.views import OrderCreateView,OrderCompleteView # PwA 2.0
app_name= 'mainapp'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('products/<category>', ProductListView.as_view(), name='products'), # PwA 2.0
    path('cart/<slug>', add_to_cart, name='cart'),  
    path('increase/<slug>', increase_cart, name='increase-cart'),  
    path('decrease/<slug>', decrease_cart, name='decrease-cart'),  
    path('cart/', CartListView.as_view(), name='cart-home'),  
    path('orders/new/', OrderCreateView.as_view(), name='create-order'),
    path('orders/complete/<int:pk>', OrderCompleteView.as_view(),name='complete-order'),
]

PwA Store 2.0/templates/base.html
<!--templates/base.html-->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css" rel="stylesheet">
  <title>PwA Store | pythonwithai.com</title>
</head>
<body>
  {% include 'navbar.html' %}
    {% if messages %}
    <div class="messages container mt-2">
        {% for message in messages %}
        <div {% if message.tags %} class="alert alert-{{ message.tags }}{% endif %}" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
        </div>
        {% endfor %}
    </div>
  {% endif %}
  <main>
    <div class="container">
      {% block content %}
      {% endblock content %}
    </div>
  </main>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

PwA Store 2.0/templates/navbar.html
<!-- templates/navbar-->
{% load cart_tag %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
  <a class="navbar-brand" href="/">PwA Store</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li {% if request.path == 'contact' %}class="nav-item active"{% else %}class="nav-item"{% endif %}>
        <!--PwA 2.0-->
        <a class="nav-link" href="{% url 'mainapp:products' category='T-Shirt' %}">T-Shirts <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <!--PwA 2.0-->
        <a class="nav-link" href="{% url 'mainapp:products' category='Cap' %}">Caps</a>
      </li>
      <li class="nav-item">
        <!--PwA 2.0-->
        <a class="nav-link" href="{% url 'mainapp:products' category='Shoes' %}">Shoes</a>
      </li>
      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'mainapp:cart-home' %}">
          <i class="fa fa-shopping-cart"></i> Cart
          <span class="badge badge-light">{{ request.user| cart_total_quantity }}</span>
        </a>
      </li>
       <li class="nav-item">
        <a class="nav-link" href="">
          <i class="fas fa-user"></i> Hi {{ request.user.username }}!
        </a>        
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}"> Log Out</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a  class="btn btn" href="{% url 'login' %}">Log In</a>
      </li>
      <li><span>&nbsp;&nbsp;&nbsp;</span></li>
      <li class="nav-item">
        <a  class="btn btn-primary" href="{% url 'signup' %}">Sign Up</a>
      </li>
      {% endif %}
    </ul>
  </div>
  </div>
</nav>